
---
include:
  - board: nice_nano//zmk
    shield: charybdis_left
  - board: nice_nano//zmk
    shield: charybdis_right
    snippet: zmk-usb-logging
  - board: nice_nano//zmk
    shield: settings_reset
